// Mocks generated by Mockito 5.x for use in Flutter tests.
// Run `flutter pub run build_runner build` to regenerate.
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart';
import 'package:voice_app/features/assets/assets.dart';
import 'package:voice_app/features/assets/repository/asset_remote_data_source.dart';

// ── MockIAssetRepository ──────────────────────────────────────────────────

class MockIAssetRepository extends Mock implements IAssetRepository {
  @override
  Future<AssetCatalog?> getCatalog({bool forceRefresh = false}) =>
      super.noSuchMethod(
        Invocation.method(#getCatalog, [], {#forceRefresh: forceRefresh}),
        returnValue: Future.value(null),
        returnValueForMissingStub: Future.value(null),
      ) as Future<AssetCatalog?>;

  @override
  Future<String?> ensureFileCached({
    required String hash,
    required String url,
    required String ext,
  }) =>
      super.noSuchMethod(
        Invocation.method(#ensureFileCached, [], {#hash: hash, #url: url, #ext: ext}),
        returnValue: Future.value(null),
        returnValueForMissingStub: Future.value(null),
      ) as Future<String?>;

  @override
  Future<void> clearAll() =>
      super.noSuchMethod(
        Invocation.method(#clearAll, []),
        returnValue: Future.value(),
        returnValueForMissingStub: Future.value(),
      ) as Future<void>;
}

// ── MockAssetRemoteDataSource ─────────────────────────────────────────────

class MockAssetRemoteDataSource extends Mock implements AssetRemoteDataSource {
  @override
  Future<CatalogFetchResult> fetchCatalog({String? cachedEtag}) =>
      super.noSuchMethod(
        Invocation.method(#fetchCatalog, [], {#cachedEtag: cachedEtag}),
        returnValue: Future.value(const CatalogFetchError(message: 'mock')),
        returnValueForMissingStub: Future.value(const CatalogFetchError(message: 'mock')),
      ) as Future<CatalogFetchResult>;

  @override
  Future<List<int>?> downloadFile(String url) =>
      super.noSuchMethod(
        Invocation.method(#downloadFile, [url]),
        returnValue: Future.value(null),
        returnValueForMissingStub: Future.value(null),
      ) as Future<List<int>?>;
}
